### ISSUE TITLE
Error in WSL without $PATH including path to powershell.exe

### ISSUE THREAD

**Issue by mfmayer** [dzylikecode/Inspire-VSCodeExt-Paste-Image#16]
In case $PATH is not containing the path to the powershell.exe within WSL, then the following error is coming when pasting an image:
`powershell.exe EOENT error`

Eventually full qualified path of powershell.exe should be used to spawn it in order to check if current clipboard format is an image.

**Comment by dzylikecode** [comment]
Why not append such to `.bashrc`:

```bash
alias powershell.exe=/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
```

If you dislike polluting `.bashrc`, I will accept your advice to use the full path of Powershell instead.

**Comment by mfmayer** [comment]
I did exactly this, but it took me some time to find out that this is causing the error. Maybe you can add this in the readme to check and eventually add powershell.exe’s path to $PATH. I assume that more people are not adopting their windows environment variables into WSL, what actually caused that it was not part of $PATH.

**Comment by dzylikecode** [comment]
I'm so sorry that it took you time to find out the bug caused by my thoughtlessness. Thanks for your patience and suggestions.
