### ISSUE TITLE
[FeatureRequest]: rename the image before pasting it 

### ISSUE THREAD

**Issue by imdouyu** [dzylikecode/Inspire-VSCodeExt-Paste-Image#18]
reference: https://marketplace.visualstudio.com/items?itemName=sakamoto66.vscode-paste-image

**Comment by dzylikecode** [comment]
full path or just a name?

| full path | just name |
| :--: | :--: |
|![image](https://user-images.githubusercontent.com/71511961/219956514-912d5d8a-7148-43d1-95f1-54f8077958e0.png)| ![image](https://user-images.githubusercontent.com/71511961/219956591-a0bb0db6-5993-4435-a56e-f5dac1dea447.png)|

**Comment by imdouyu** [comment]
Only name, or you can add option for broad use.

**Comment by dzylikecode** [comment]
![image](https://user-images.githubusercontent.com/71511961/219988693-31bde88a-ad51-418c-bf79-c0f5493b6f58.png)

now you can do what you favor. 😄

**Comment by imdouyu** [comment]
Thanks.
