### ISSUE TITLE
[Feature suggestion] CurrentFileName function support.

### ISSUE THREAD

**Issue by maxshiro** [dzylikecode/Inspire-VSCodeExt-Paste-Image#21]
Can add functions like ${currentFileName} and ${currentFileNameWithoutExt} in a similar way to [dendron-paste-image](https://github.com/dendronhq/dendron-paste-image)?
可以添加类似于[dendron-paste-image](https://github.com/dendronhq/dendron-paste-image)中的`${currentFileName}`
`${currentFileNameWithoutExt}`函数吗？

I recently found that the plugin I was using before is no longer working, and I discovered your plugin [telesoho/vscode-markdown-paste-image](https://github.com/telesoho/vscode-markdown-paste-image/issues/88#issuecomment-1266563769) here, and I'm glad it's working properly on my computer. However, my habit is to store images in a folder with the same name, so...
最近发现之前使用的插件失效了，我在这里发现了您的插件[telesoho/vscode-markdown-paste-image](https://github.com/telesoho/vscode-markdown-paste-image/issues/88#issuecomment-1266563769)，很高兴它在我的电脑上正常工作。但是我的使用习惯是将图片存放到同名文件夹内。所以。

**Comment by dzylikecode** [comment]
抱歉，很晚才看到，我会添加这个功能的。

**Comment by dzylikecode** [comment]
添加了你想要的功能，你可以试试，在设置里面setting里面设置`${currentFileDir}/${currentFileNameWithoutExt}`

**Comment by FuckBound** [comment]
非常感谢, 这也是我需要的
