### ISSUE TITLE
添加自定义文件名称功能

### ISSUE THREAD

**Issue by Hoysion** [dzylikecode/Inspire-VSCodeExt-Paste-Image#23]
你好，作者，特别喜欢你的插件，如果可以自定义文件名就更好了。
类似Paste Image的功能，可以使用年月日时分秒或者时间戳等进行命名，只需要用momentjs的format函数即可，如下：
![image](https://github.com/dzylikecode/Inspire-VSCodeExt-Paste-Image/assets/57893875/35978608-a238-4ccf-a6e7-2bed765ef254)

**Comment by dzylikecode** [comment]
你是要自己定义其格式吗

**Comment by dzylikecode** [comment]
过几分钟后应该可以更新了. 不过, 我没有检验文件名是否有效, 比如Windows中不能含有`><:`等字符.

**Comment by Hoysion** [comment]
没事，只能由用户按照format方法的指定格式配置就行。谢谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tatu ***@***.***&gt;; 
发送时间: 2024年4月23日(星期二) 下午2:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dzylikecode/Inspire-VSCodeExt-Paste-Image] 添加自定义文件名称功能 (Issue #23)














 
过几分钟后应该可以更新了. 不过, 我没有检验文件名是否有效, 比如Windows中不能含有&gt;<:等字符.
