### ISSUE TITLE
可以配置不加密文件名么

### ISSUE THREAD

**Issue by npmrun** [dzylikecode/Inspire-VSCodeExt-Paste-Image#24]
![image](https://github.com/user-attachments/assets/5c744398-e9b0-4712-a2f4-6e7d350e883a)
加密之后的文件名好像和kisstkondoros.vscode-gutter-preview插件冲突，导致无法预览

**Comment by dzylikecode** [comment]
有这个路径的文件吗,应该是kisstkondoros.vscode-gutter-preview无法预览这个路径的文件吧

**Comment by npmrun** [comment]
有这个，基于打开的项目文件夹的绝对路径，应该是它无法预览，我看怎么改下
