### ISSUE TITLE
command 'md-paste-enhanced.paste' not found

### ISSUE THREAD

**Issue by maxshiro** [dzylikecode/Inspire-VSCodeExt-Paste-Image#25]
当我尝试粘贴时爆出了这个错误
command 'md-paste-enhanced.paste' not found

**Comment by dzylikecode** [comment]
可以详细描述吗,我不知道如何复现

**Comment by dzylikecode** [comment]
是不是没更新还是说和你的上一个denron paste image 冲突了, 我在wsl中测试时正常的



https://github.com/user-attachments/assets/cd40d1fa-fd16-4dbb-ba82-7bc8ab8c46e1

**Comment by JunzheShen** [comment]
您好，我也遇到了同样的问题，操作系统是MacOS 14.6，vscode版本如下所示。但是奇怪的是我的Windows PC并没有发现这个问题，PC是Windows10，vscode版本1.89.1。插件版本都是最新版
```
版本: 1.92.2 (Universal)
提交: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
日期: 2024-08-14T17:29:30.058Z (1 周前)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by JunzheShen** [comment]
我查看了插件的输出，发现了如下报错
```
2024-08-26 01:08:40.785 [error] Activating extension dzylikecode.md-paste-enhanced failed due to an error:
2024-08-26 01:08:40.785 [error] TypeError: Cannot read properties of undefined (reading 'saveImage')
	at /Users/shenjunzhe/.vscode/extensions/dzylikecode.md-paste-enhanced-2.11.2/out/extension.js:3:8533
	at /Users/shenjunzhe/.vscode/extensions/dzylikecode.md-paste-enhanced-2.11.2/out/extension.js:1:203
	at /Users/shenjunzhe/.vscode/extensions/dzylikecode.md-paste-enhanced-2.11.2/out/extension.js:6:58096
	at /Users/shenjunzhe/.vscode/extensions/dzylikecode.md-paste-enhanced-2.11.2/out/extension.js:1:203
	at Object.<anonymous> (/Users/shenjunzhe/.vscode/extensions/dzylikecode.md-paste-enhanced-2.11.2/out/extension.js:6:62195)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:2:1257)
	at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
	at Module.load (node:internal/modules/cjs/loader:1215:32)
	at Module._load (node:internal/modules/cjs/loader:1031:12)
	at c._load (node:electron/js2c/node_init:2:13801)
	at E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:177:6051)
	at i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:31787)
	at o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:139:34334)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:3:98)
	at m.xb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:32966)
	at async Promise.all (index 0)
```
这导致该插件的另一个命令(创建空文件)也是找不到的，请问应该如何解决这个问题呢？

**Comment by dzylikecode** [comment]
不好意思, 我没有 mac 环境, 我就没有添加关于 mac 的支持. 因为没法调试 我就不知道自己写的对不

**Comment by JunzheShen** [comment]
> 不好意思, 我没有 mac 环境, 我就没有添加关于 mac 的支持. 因为没法调试 我就不知道自己写的对不

您好，我不太懂前端开发这方面，我在您的代码里翻到了这段代码，这是否意味着在macOS上本身就是无法运行的呢？
```
function Clipboard() {
  const platform = process.platform;
  if (platform == "win32") {
    return new ClipboardWin();
  } else if (isWsl) {
    return new ClipboardWSL();
  }
}
```

**Comment by dzylikecode** [comment]
是的，我没有添加，你要添加可以，那就是你要在你电脑上测试一下了，等一下我可以发一下流程和更新一下代码，你试一试

**Comment by dzylikecode** [comment]
你可以克隆仓库试试, 在 mac 分支

这是[指示](https://github.com/dzylikecode/Inspire-VSCodeExt-Paste-Image/blob/mac/README_zh.md)

**Comment by JunzheShen** [comment]
> 你可以克隆仓库试试, 在 mac 分支
> 
> 这是[指示](https://github.com/dzylikecode/Inspire-VSCodeExt-Paste-Image/blob/mac/README_zh.md)

好的，谢谢您

**Comment by JunzheShen** [comment]
> 你可以克隆仓库试试, 在 mac 分支
> 
> 这是[指示](https://github.com/dzylikecode/Inspire-VSCodeExt-Paste-Image/blob/mac/README_zh.md)
<img width="1390" alt="Snipaste_2024-08-26_17-47-04" src="https://github.com/user-attachments/assets/eab53238-bd98-43a6-9379-df88c3bfb505">

您好，我测试了一下插件，应该是可以正常工作的，粘贴的代码是我自己之前设置过的，可能是自动读到了相关的配置文件吧？请问这版插件是否可以更新到插件市场呢？十分感谢！

**Comment by dzylikecode** [comment]
好的

**Comment by JunzheShen** [comment]
> > 好的
> 
> 我也看了一下插件输出，但是我看不太懂... 我把除了这个插件所有插件都卸载了，还是同样的报错
> 
> ```
> 2024-09-07 15:14:30.883 [error] Activating extension dzylikecode.md-paste-enhanced failed due to an error:
> 2024-09-07 15:14:30.883 [error] TypeError: Cannot read properties of undefined (reading 'saveImage')
> 	at /root/.vscode-server/extensions/dzylikecode.md-paste-enhanced-2.12.0/out/extension.js:30:694
> 	at /root/.vscode-server/extensions/dzylikecode.md-paste-enhanced-2.12.0/out/extension.js:1:141
> 	at /root/.vscode-server/extensions/dzylikecode.md-paste-enhanced-2.12.0/out/extension.js:33:58096
> 	at /root/.vscode-server/extensions/dzylikecode.md-paste-enhanced-2.12.0/out/extension.js:1:141
> 	at Object.<anonymous> (/root/.vscode-server/extensions/dzylikecode.md-paste-enhanced-2.12.0/out/extension.js:33:62195)
> 	at Module._compile (node:internal/modules/cjs/loader:1358:14)
> 	at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
> 	at Module.load (node:internal/modules/cjs/loader:1208:32)
> 	at Module._load (node:internal/modules/cjs/loader:1024:12)
> 	at y._load (/root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/out/vs/workbench/api/node/extensionHostProcess.js:184:6031)
> 	at i._load (/root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/out/vs/workbench/api/node/extensionHostProcess.js:181:32144)
> 	at n._load (/root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/out/vs/workbench/api/node/extensionHostProcess.js:146:34326)
> 	at Module.require (node:internal/modules/cjs/loader:1233:19)
> 	at require (node:internal/modules/helpers:179:18)
> 	at i (/root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/out/bootstrap-fork.js:3:98)
> 	at m.xb (/root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/out/vs/workbench/api/node/extensionHostProcess.js:181:33345)
> 	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 	at async Promise.all (index 0)
> ```

怎么感觉跟我的报错是差不多的？我的那个问题在于我的操作系统没有在下面这个代码里支持，没有返回ClipboardWin/ClipboardWSL对象，最新版本应该还会加一个ClipboardMac(大概是这个名字)
```
function Clipboard() {
  const platform = process.platform;
  if (platform == "win32") {
    return new ClipboardWin();
  } else if (isWsl) {
    return new ClipboardWSL();
  }
}
```

**Comment by dzylikecode** [comment]
你是在什么系统上跑的, 我已经添加了 mac 了. Linux 的话, 我没有添加

**Comment by dzylikecode** [comment]
你的环境里面有node吗, 有的话, 你可以运行一下下面的代码试试吗

```js
'use strict';
const os = require('os');
const fs = require('fs');
const isDocker = require('is-docker');

const isWsl = () => {
	if (process.platform !== 'linux') {
		return false;
	}

	if (os.release().toLowerCase().includes('microsoft')) {
		if (isDocker()) {
			return false;
		}

		return true;
	}

	try {
		return fs.readFileSync('/proc/version', 'utf8').toLowerCase().includes('microsoft') ?
			!isDocker() : false;
	} catch (_) {
		return false;
	}
};

console.log(isWsl())
```

**Comment by dzylikecode** [comment]
你这个是 wsa 吗, wsa 也可以运行 code 吗
