### ISSUE TITLE
how to compress the extension

### ISSUE THREAD

**Issue by dzylikecode** [dzylikecode/Inspire-VSCodeExt-Paste-Image#5]
It reminds me when I package the extension:

> This extension consists of 545 files, out of which 528 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore

So how to compress it?

**Comment by dzylikecode** [comment]
I need your help @worranhin

**Comment by worranhin** [comment]
The website you quote seems clear. What's the problem you met? @dzylikecode 

If you use webpack, maybe [this tool](https://createapp.dev/) can help.

**Comment by dzylikecode** [comment]
I just write several javascript lines, but the size it builds is 1MB. That's terrible.

**Comment by worranhin** [comment]
Is it because the dependencies?

Maybe try to split the bundle? 

https://www.webpackjs.com/guides/code-splitting/
